{{ config(materialized='table') }}

select
    trim(record_id)                                     as record_id,
    trim(mission_name)                                  as mission_name,
    trim(mission_type)                                  as mission_type,
    trim(lead_country)                                  as lead_country,
    trim(lead_iso_code)                                 as lead_iso_code,
    trim(lead_country_region)                           as lead_country_region,
    trim(operation_location)                            as operation_location,
    trim(operation_region)                              as operation_region,
    trim(threat_level)                                  as threat_level,
    trim(command_hq)                                    as command_hq,
    trim(operation_start_year)                          as operation_start_year,
    trim(operation_end_year)                            as operation_end_year,
    trim(duration_years)                                as duration_years,
    trim(mission_phase)                                 as mission_phase,
    trim(troops_deployed)                               as troops_deployed,
    trim(air_assets_deployed)                           as air_assets_deployed,
    trim(naval_assets_deployed)                         as naval_assets_deployed,
    trim(casualties)                                    as casualties,
    trim(casualties_rate_pct)                           as casualties_rate_pct,
    trim(mission_cost_m_usd)                            as mission_cost_m_usd,
    trim(cost_per_soldier_usd)                          as cost_per_soldier_usd,
    trim(contributing_countries_count)                  as contributing_countries_count,
    upper(trim(nato_led))                               as nato_led,
    upper(trim(un_mandate))                             as un_mandate,
    trim(mission_outcome)                               as mission_outcome,
    trim(mission_status)                                as mission_status,
    trim(classification)                                as classification,
    trim(media_coverage)                                as media_coverage,
    trim(public_support_pct)                            as public_support_pct,
    trim(after_action_report)                           as after_action_report,
    _source_file,
    _loaded_at
from {{ source('bronze_raw', 'nato_operations_missions') }}
