COPY INTO BRONZE_DB.PUBLIC.NATO_COUNTRY_STATS
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,
           $15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,
           METADATA$FILENAME,
           CURRENT_TIMESTAMP()
    FROM @BRONZE_DB.PUBLIC.NATO_RAW_STAGE/NATO_1_Country_Stats.csv
)
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('', '-'));

COPY INTO BRONZE_DB.PUBLIC.NATO_EQUIPMENT_INVENTORY
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,
           $15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,
           METADATA$FILENAME,
           CURRENT_TIMESTAMP()
    FROM @BRONZE_DB.PUBLIC.NATO_RAW_STAGE/NATO_2_Equipment_Inventory.csv
)
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('', '-'));

COPY INTO BRONZE_DB.PUBLIC.NATO_OPERATIONS_MISSIONS
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,
           $16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,
           METADATA$FILENAME,
           CURRENT_TIMESTAMP()
    FROM @BRONZE_DB.PUBLIC.NATO_RAW_STAGE/NATO_3_Operations_Missions.csv
)
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('', '-'));

COPY INTO BRONZE_DB.PUBLIC.NATO_MISSION_PARTICIPANTS
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
           METADATA$FILENAME,
           CURRENT_TIMESTAMP()
    FROM @BRONZE_DB.PUBLIC.NATO_RAW_STAGE/NATO_4_Mission_Participants.csv
)
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('', '-'));